export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGINCODE_REQUEST = 'LOGINCODE_REQUEST';
export const LOGINCODE_SUCCESS = 'LOGINCODE_SUCCESS';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const APP_ALERT = 'APP_ALERT';
export const APP_ALERT_CLEAR = 'APP_ALERT_CLEAR';
